/**
 * PDF export service.
 *
 * Uses expo-print to render HTML to PDF, then expo-sharing to let the
 * user save / share / send to their doctor.
 */

import * as Print from "expo-print";
import * as Sharing from "expo-sharing";

export interface DoctorSummaryDocument {
  patientName: string;
  generatedAt: string;
  patientContext: string;
  vitalsSummary: string;
  symptomSummary: string;
  moodSummary: string;
  riskFactors: string[];
  questionsToAsk: string[];
  urgentConcerns: string[];
}

export async function exportDoctorSummary(doc: DoctorSummaryDocument): Promise<void> {
  const html = renderDoctorSummaryHtml(doc);
  const { uri } = await Print.printToFileAsync({ html, base64: false });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { dialogTitle: "Share with your provider" });
  }
}

function renderDoctorSummaryHtml(doc: DoctorSummaryDocument): string {
  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Visit Summary</title>
  <style>
    body { font-family: -apple-system, system-ui, sans-serif; color: #2A1A1F; padding: 36px; line-height: 1.5; }
    h1 { font-size: 24px; margin: 0 0 4px; color: #B85F71; }
    h2 { font-size: 16px; margin: 24px 0 6px; color: #2A1A1F; border-bottom: 1px solid #EFE0DC; padding-bottom: 4px; }
    p, li { font-size: 13px; }
    ul { padding-left: 18px; }
    .meta { color: #8C7C84; font-size: 11px; margin-bottom: 18px; }
    .urgent { background: #F7DDD8; padding: 12px; border-radius: 8px; margin: 16px 0; }
  </style>
</head>
<body>
  <h1>Visit Summary</h1>
  <div class="meta">Patient: ${escapeHtml(doc.patientName)} · Generated ${escapeHtml(doc.generatedAt)}</div>

  ${doc.urgentConcerns.length > 0 ? `<div class="urgent"><strong>Urgent concerns</strong><ul>${doc.urgentConcerns.map((c) => `<li>${escapeHtml(c)}</li>`).join("")}</ul></div>` : ""}

  <h2>Patient context</h2>
  <p>${escapeHtml(doc.patientContext)}</p>

  <h2>Vitals (past 30 days)</h2>
  <p>${escapeHtml(doc.vitalsSummary)}</p>

  <h2>Symptoms</h2>
  <p>${escapeHtml(doc.symptomSummary)}</p>

  <h2>Mood</h2>
  <p>${escapeHtml(doc.moodSummary)}</p>

  <h2>Risk factors</h2>
  <ul>${doc.riskFactors.map((r) => `<li>${escapeHtml(r)}</li>`).join("")}</ul>

  <h2>Questions to ask</h2>
  <ul>${doc.questionsToAsk.map((q) => `<li>${escapeHtml(q)}</li>`).join("")}</ul>

  <p class="meta">Generated by Kairos. This summary is intended to support — not replace — clinical judgement.</p>
</body>
</html>`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
